//This is for ai profiles generated by AI
const CommunicationInstructions = (sequelize, Sequelize) => {
  const Values = sequelize.define("CommunicationInstructions", {
    title: {
      type: Sequelize.STRING,
      defaultValue: "", //optional
    },
    description: {
      type: Sequelize.STRING,
      defaultValue: "",
    },
    type: {
      type: Sequelize.STRING,
      defaultValue: "ai", // "ai", "manual"
    },
    userId: {
      type: Sequelize.INTEGER,
      allowNull: true,
      references: {
        model: "Users", // Table name (plural form)
        key: "id",
      },
    },
  });

  return Values;
};

export default CommunicationInstructions;
