//This is for ai profiles generated by AI
const CustomAction = (sequelize, Sequelize) => {
  const User = sequelize.define("CustomAction", {
    type: {
      type: Sequelize.STRING,
      defaultValue: "booking", // "booking", "availability", "kb"
    },
    actionId: {
      type: Sequelize.STRING, // id of the action on the synthflow
      allowNull: true,
    },
    userId: {
      type: Sequelize.INTEGER,
      allowNull: true,
      references: {
        model: "Users", //
        key: "id",
      },
    },
  });

  return User;
};

export default CustomAction;
