//This is for ai profiles generated by AI
const CustomAction = (sequelize, Sequelize) => {
  const User = sequelize.define("CustomAction", {
    profileData: {
      type: Sequelize.TEXT("medium"),
      allowNull: true,
    },
    userId: {
      type: Sequelize.INTEGER,
      allowNull: true,
      references: {
        model: "Users", // Table name (plural form)
        key: "id",
      },
    },
  });

  return User;
};

export default CustomAction;
