//This is for ai profiles generated by AI
const DonotDiscuss = (sequelize, Sequelize) => {
  const Values = sequelize.define("DonotDiscuss", {
    // title: {
    //   type: Sequelize.STRING(255),
    //   defaultValue: "", //optional
    // },
    description: {
      type: Sequelize.STRING(255),
      defaultValue: "",
    },
    type: {
      type: Sequelize.STRING(255),
      defaultValue: "ai", // "ai", "manual"
    },
    userId: {
      type: Sequelize.INTEGER,
      allowNull: true,
      references: {
        model: "Users", // Table name (plural form)
        key: "id",
      },
    },
  });

  return Values;
};

export default DonotDiscuss;
