//This is for ai profiles generated by AI
const ObjectionHandling = (sequelize, Sequelize) => {
  const FrameworkAndTechnique = sequelize.define("ObjectionHandling", {
    objectionType: {
      type: Sequelize.STRING,
      defaultValue: "",
    },
    prompt: {
      type: Sequelize.STRING,
      defaultValue: "",
    },
    response: {
      type: Sequelize.TEXT("medium"),
      allowNull: true,
    },

    type: {
      type: Sequelize.STRING,
      defaultValue: "ai", // "ai", "manual"
    },
    kbType: {
      type: Sequelize.STRING,
      defaultValue: "", //video, kb
    },
    kbId: {
      type: Sequelize.INTEGER,
      allowNull: true,
    },
    userId: {
      type: Sequelize.INTEGER,
      allowNull: true,
      references: {
        model: "Users", // Table name (plural form)
        key: "id",
      },
    },
  });

  return FrameworkAndTechnique;
};

export default ObjectionHandling;
